Repository shawnlong636/CS166-Online-Messaging-System, pull requests merged in 2022-03, with the labels that each got.

#21 1 add remaining lab scripts
  java/classes/ProfNetwork.class
  java/src/ProfNetwork.java
  sql/scripts/create_db.sh
  sql/scripts/startPostgreSQL.sh
  sql/scripts/stopPostgreDB.sh
  sql/src/create_tables.sql
Labels: bug

#22 GUI V1.1
  .gitignore
  java/lib/activation.jar
  java/src/ChangePassword.java
  java/src/Connection_Request.java
  java/src/FrameViewer.java
  java/src/Friends.java
  java/src/GUI.java
  java/src/Messages.java
  java/src/Search.java
  java/src/SubScreen.java
  java/src/UserInfo.java
Labels: enhancement

#24 Shawnlong636/feature mockups
  .gitignore
  README.md
  docs/CommandLineDriver.md
  docs/ProfNetwork.md
  java/scripts/compile.sh
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
  sql/scripts/startPostgreSQL.sh
Labels: documentation, enhancement

#26 G UI v1.2
  Database.txt
  java/src/GUI.java
Labels: enhancement

#32 Shawnlong636/create user
  java/src/ProfNetwork.java
Labels: enhancement

#33 Shawnlong636/change password
  .gitignore
  data/connection_usr.csv
  data/educational_details.csv
  data/usr.csv
  data/work_expr.csv
  java/classes/ProfNetwork.class
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
  sql/src/load_data.sql
Labels: enhancement

#30 GUI V1.3
  Database.txt
  java/src/ChangePassword.java
  java/src/Connection_Request.java
  java/src/FrameViewer.java
  java/src/Friends.java
  java/src/GUI.java
  java/src/Messages.java
  java/src/Search.java
  java/src/SubScreen.java
Labels: documentation

#34 Shawnlong636/friend list
  java/classes/ProfNetwork.class
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
Labels: enhancement

#36 Shawnlong636/friend requests
  data/connection_usr.csv
  data/friends.csv
  data/requests.csv
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
  sql/scripts/create_db.sh
  sql/src/create_index.sql
  sql/src/create_indexes.sql
  sql/src/create_tables.sql
  sql/src/create_triggers.sql
  sql/src/load_data.sql
Labels: enhancement

#37 Manage requests
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
Labels: enhancement

#38 Manage profiles
  java/src/CommandLineDriver.java
  java/src/ProfNetwork.java
Labels: enhancement

#39 documentation updates
  Database.txt
  docs/CommandLineDriver.md
  docs/ProfNetwork.md
  java/src/CommandLineDriver.java
  java/src/GUI.java
  java/src/ProfNetwork.java
Labels: documentation

#35 updated messages tab
  data/friends 2.csv
  data/message 2.csv
  data/usr 2.csv
  java/src/GUI.java
Labels: enhancement
